# Site settings
title:
email:
description: > # this means to ignore newlines until "baseurl:"
  Proudly affiliated with the Fayette County Chamber of Commerce, the 
  Fayette Young Professionals Network (FYPN) is the premiere organization 
  for connecting, supporting, and growing Fayette County's young 
  professional population! We accomplish our goals through regular casual 
  meetings, professional networking and enrichment events, and by 
  supporting the next generation of Fayette County's workforce.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://billtalkington.github.io" # the base hostname & protocol for your site

# User setting
owner: Fayette Young Professionals Network
email: info@fayetteyoungprofessionals.org
facebook_username: Fayette-Young-Professionals-135125349889727/
twitter_username: youngfayette
address:
  - line: 65 W Main St. Suite 107 
  - line: Uniontown, PA 15401
  # Feel free to add more lines here 
telephone: (724)-437-4571
copyright:

# Use this if we want to map HQ on google maps...or better yet, OSM!
# API settings
google_api_key:

# Build settings
markdown: kramdown

# gems: [bourbon, bitters]
